<a href="https://colab.research.google.com/github/paulinad98/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

np.__version__

print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'add', 'add_docs

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype


dtype('float64')

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x = np.array(
    [[[4, 2, 10],
     [3, 1, 2]],

    [[2, 2, 4],
     [4, 2, 1]]]
)
x

array([[[ 4,  2, 10],
        [ 3,  1,  2]],

       [[ 2,  2,  4],
        [ 4,  2,  1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype = np.uint8)

In [ ]:
A.dtype

dtype('uint8')

In [3]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(start=5, stop = 10)

array([5, 6, 7, 8, 9])

In [12]:
np.arange(start=0, stop = 1, step = 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [16]:
np.linspace(start=0,stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
A = np.array([1, 2, 3, 4])
B = np.array([3, 4, 5, 6])
print(A)
print(B)

[1 2 3 4]
[3 4 5 6]


In [21]:
A+B

array([ 4,  6,  8, 10])

In [22]:
A-B

array([-2, -2, -2, -2])

In [23]:
A * B

array([ 3,  8, 15, 24])

In [24]:
A / B

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [25]:
A - 2

array([-1,  0,  1,  2])

In [26]:
np.add(A, B)

array([ 4,  6,  8, 10])

In [27]:
np.subtract(A, B)

array([-2, -2, -2, -2])

In [28]:
np.multiply(A, B)

array([ 3,  8, 15, 24])

In [29]:
np.divide(A,B)

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [33]:
X = np.array([[1, 3], [2, 5]])
Y = np.array([[2, 3], [-5, 5]])
print(X, '\n')
print(Y)

[[1 3]
 [2 5]] 

[[ 2  3]
 [-5  5]]


In [34]:
X*Y

array([[  2,   9],
       [-10,  25]])

In [35]:
np.dot(X,Y)

array([[-13,  18],
       [-21,  31]])

In [36]:
X @ Y

array([[-13,  18],
       [-21,  31]])

In [37]:
np.random.seed(0)

In [38]:
np.random.randn()

1.764052345967664

In [40]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [41]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [42]:
np.random.rand()

0.1965823616800535

In [43]:
np.random.randint(10)

0

In [46]:
np.random.randint(low=10, high=101)

79

In [47]:
np.random.randint(low=10, high=101, size=11)

array([10, 60, 46, 44, 58, 13, 52, 87, 31, 83, 10])

In [48]:
np.random.choice([1, 2, 5, 6])

5

In [49]:
np.random.choice(["c++", "siedem", "python"])

'python'

In [51]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.random.shuffle(data)
data

array([9, 0, 6, 4, 5, 3, 8, 1, 2, 7])

In [53]:
np.exp(1)

2.718281828459045

In [54]:
np.sqrt(4)

2.0

In [56]:
np.all([2, 3, 0])

False

In [58]:
np.any([0, 1, 0])

True

In [59]:
bool(0)

False

In [64]:
A = np.random.rand(5)
A

array([0.28940609, 0.18319136, 0.58651293, 0.02010755, 0.82894003])

In [65]:
np.argmax(A)

4

In [66]:
A[np.argmax(A)]

0.8289400292173631

In [67]:
np.argmin(A)

3

In [68]:
np.argsort(A)

array([3, 1, 0, 2, 4])

In [69]:
np.max(A)

0.8289400292173631

In [70]:
np.mean(A)

0.3816315930338516

In [71]:
np.median(A)

0.2894060929472011

In [72]:
np.std(A)

0.2900499632454077