<a href="https://colab.research.google.com/github/paulinad98/data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.__version__

print(dir(np))

In [ ]:
help(np.array)

In [10]:
x = np.array([1, 3])
x

array([1, 3])

In [11]:
print(x)

[1 3]


In [12]:
type(x)

numpy.ndarray

In [13]:
x.ndim

1

In [14]:
x.shape

(2,)

In [15]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [18]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [19]:
x.dtype


dtype('float64')

In [22]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [27]:
x = np.array(
    [[[4, 2, 10],
     [3, 1, 2]],

    [[2, 2, 4],
     [4, 2, 1]]]
)
x

array([[[ 4,  2, 10],
        [ 3,  1,  2]],

       [[ 2,  2,  4],
        [ 4,  2,  1]]])

In [28]:
x.ndim

3

In [29]:
x.shape

(2, 2, 3)

In [30]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [31]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [35]:
A = np.array([24, 120, 230], dtype = np.uint8)

In [36]:
A.dtype

dtype('uint8')